FROM gradle:7.3.1-jdk17 AS builder

WORKDIR /home/gradle/project
COPY --chown=gradle:gradle . .

# Run the test
CMD ["gradle", "test", "--tests", "com.example.team1_be.domain.Schedule.Recommend.ScheduleGeneratorLoadTest", "-i"]
