server:
  port: 8080
spring:
  datasource:
    url: ${DATABASE_URL}?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  sql:
    init:
      mode: always
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

jwt:
  secretKey: ${SECRET_KEY}

kakao:
  clientId: ${KAKAO_CLIENT_ID}
  redirectURI: ${KAKAO_REDIRECT_URI}
  baseURI: ${KAKAO_BASE_URI}

krampoline:
  proxy:
    hostName: ${KRAMPOLINE_PROXY_HOSTNAME}
    port: ${KRAMPOLINE_PROXY_PORT}

cors:
  origin: ${CORS_ORIGIN}

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
    '[com.example.team1_be]': INFO